name: Release

on:
  push:
    tags:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy test stub
        run: |
          echo "Testing"

  release:
    runs-on: ubuntu-latest
    needs: ["tests"]
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # tag=v3.5.2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # tag=v2.1.0

      - name: Docker Login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # tag=v4.0.1
        with:
          go-version-file: "go.mod"
          cache: true

      - uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9 # tag=v3.0.5

      # To be compatible with ENVs in PRs
      - name: Get SHA that triggered release
        run: |
          echo -n "HEAD_SHA=" >>${GITHUB_ENV}
          git rev-parse --short $GITHUB_SHA >>${GITHUB_ENV}

      - name: Make release
        uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # tag=v4.2.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
