name: Run tests

on: [ pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # tag=v3.6.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # tag=v4.0.1
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@c001ccfb5aff62e28bda6a6c39b59a7e061be5b9 # tag=v1.2.0

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

      - name: Lint
        run: |
          make lint

      - name: Setup test environment
        run: |
          make gateway-api-upstream-get all-setup

      - name: Run tests
        run: |
          make test-run
