name: Run tests

on: [ pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # tag=v4.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # tag=v4.1.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@c001ccfb5aff62e28bda6a6c39b59a7e061be5b9 # tag=v1.2.0

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

      - name: Lint
        run: |
          make lint

      - name: Setup test environment
        run: |
          make gateway-api-upstream-get all-setup

      - name: Run tests
        run: |
          make test-run
